// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://effnqthzxoslesrcukfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZm5xdGh6eG9zbGVzcmN1a2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxODAyODksImV4cCI6MjA2Nzc1NjI4OX0.-pfKIZPyXCJRlmjGV-DaYLtq2pyzkbehqVZcBVuwRmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});